[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 5173
  framework = "#custom"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200